# Template for the configurations.

train_dataloader:
  args:
    arg1: ...
    arg2: ...
  dataset: 
    name: ... 
    args:
      arg1: ...
      arg2: ...
    transform:
      name: ...
      args:
        arg1: ...
        arg2: ...

val_dataloader: 
  batch_size: ...
  dataset:
    name: ...
    args:
      arg1: ...
      arg2: ...
    transform:
      name: ...
      args:
        arg1: ...
        arg2: ...

model:
  name: ...
  args:
    arg1: ...
    arg2: ...

optimizer:
  name: ...
  args:
    arg1: ...
    arg2: ...

scheduler:
  name: ...
  args:
    arg1: ...
    arg2: ...

loss:
  name: ...
  args:
    arg1: ...
    arg2: ...
